<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Project</name>
   <tag></tag>
   <elementGuidId>6a858706-9d60-4923-8107-50238d993140</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Project</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_C001_divContent&quot;)/div[@class=&quot;trmBodyContent&quot;]/div[@class=&quot;trm-pagewrap&quot;]/div[@class=&quot;trm-container&quot;]/div[@class=&quot;trm-recipe-section&quot;]/div[@class=&quot;trm-bottom-module trm-recipe-panel trm-recipe-pane&quot;]/div[@class=&quot;trm-bottom-left trm-expand text-center trm-recipe-col recipe-large&quot;]/a[@class=&quot;trackMe trm-pov-recipe&quot;]/div[@class=&quot;trm-bottom-overlay&quot;]/h3[1]</value>
   </webElementProperties>
</WebElementEntity>
