<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bt-border</name>
   <tag></tag>
   <elementGuidId>3ce91752-c160-4c0f-8f2a-88aadad7356c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MediaOMP/2018/DLH/01_DLH_T7080_DeLonghiBH18/img/barista-left.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bt-border</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_C001_divContent&quot;)/div[@class=&quot;trmBodyContent&quot;]/div[@class=&quot;trm-pagewrap&quot;]/div[@class=&quot;fullwidth_wrap trm_pov&quot;]/div[@class=&quot;trm-container&quot;]/div[@class=&quot;trm-twopanel space-between&quot;]/a[@class=&quot;trackMe&quot;]/div[@class=&quot;trm-twopanel-left&quot;]/img[@class=&quot;bt-border&quot;]</value>
   </webElementProperties>
</WebElementEntity>
