<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-rw (2)</name>
   <tag></tag>
   <elementGuidId>6d2df3b3-df1f-40f4-bd74-bb54a95f6b51</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-rw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-img</name>
      <type>Main</type>
      <value>feat-prod03.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Jergens Wet Skin Moisturizers with Deep Restoring Argan Oil, Enriching Shea Oil and Hydrating Coconut Oil.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//staging.cvs.triadretail.net/shop-assets/04_KAO_S6982_JergnsBCSupp/img/feat-prod03.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;trm-page-wrap&quot;]/div[@class=&quot;trm-width-lock trm-grid&quot;]/div[@class=&quot;trm-body-load&quot;]/div[@class=&quot;trm-bs trm-grid&quot;]/div[@class=&quot;trm-body-wrap&quot;]/div[@class=&quot;trm-grid&quot;]/div[@class=&quot;trm-row trm-stroke trm-feat-cats trm-tag-parent&quot;]/div[@class=&quot;trm-row&quot;]/div[@class=&quot;col-1-4&quot;]/img[@class=&quot;img-rw&quot;]</value>
   </webElementProperties>
</WebElementEntity>
