<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_product-image</name>
   <tag></tag>
   <elementGuidId>12d92aad-b82a-48ba-b108-8b10872126b5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prods&quot;)/div[@class=&quot;stp--new-product-tile-container tablet&quot;]/div[@class=&quot;tile-container&quot;]/div[@class=&quot;stp--new-product-tile stp--new-product-tile-tablet&quot;]/div[@class=&quot;product-image&quot;]</value>
   </webElementProperties>
</WebElementEntity>
