<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_MosaicTile-image (2)</name>
   <tag></tag>
   <elementGuidId>8b179b90-240f-4260-abd7-81e40380ed74</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>N-Strike Elite</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//i5.walmartimages.com/dfw/4ff9c6c9-1892/k2-_e627b00f-a7fe-4ddd-aa00-21ff877d83d9.v1.jpg?odnWidth=672&amp;odnHeight=505&amp;odnBg=ffffff</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MosaicTile-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centerContent&quot;)/div[1]/span[3]/div[@class=&quot;Mosaic ResponsiveContainer&quot;]/div[@class=&quot;MosaicLayout3Up&quot;]/div[@class=&quot;MosaicLayout3Up-col-wrap&quot;]/div[@class=&quot;MosaicLayout3Up-col-right&quot;]/a[@class=&quot;MosaicTile&quot;]/span[@class=&quot;MosaicTile-image-wrap&quot;]/img[@class=&quot;MosaicTile-image&quot;]</value>
   </webElementProperties>
</WebElementEntity>
