<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>07c6417e-9daf-42ce-86ad-2d788ed55a04</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MediaOMP/2018/CLX/01_CLX_O6252_KFBP18/img/video-thumbs/how-to-grillwithflavor.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trm-wrap&quot;)/div[@class=&quot;trm-video-section&quot;]/div[@class=&quot;trm-container&quot;]/div[@class=&quot;trm-videos-container&quot;]/div[@class=&quot;trm-video-col&quot;]/div[@class=&quot;trm-video-item&quot;]/a[@class=&quot;trackMe&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
