<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shop face</name>
   <tag></tag>
   <elementGuidId>b1584f7e-22f4-492c-8abb-ea36e8a904d5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.cvs.com/shop/content/joah-face</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trm-tr trm-cta trm-cta-black-out trm-rev</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>webtag</name>
      <type>Main</type>
      <value>ShopFace</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Shop face
                        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;trm-page-wrap&quot;]/div[@class=&quot;trm-width-lock trm-grid&quot;]/div[@class=&quot;trm-body-load&quot;]/div[@class=&quot;trm-body-wrap&quot;]/div[@class=&quot;trm-module-6&quot;]/section[@id=&quot;trm-main-pov&quot;]/div[@class=&quot;trm-grid trm-body-wrap&quot;]/div[@class=&quot;trm-main-pov&quot;]/div[@class=&quot;trm-row&quot;]/div[@class=&quot;trm-col-xs-12&quot;]/div[@class=&quot;trm-mod-content trm-face&quot;]/a[@class=&quot;trm-tr trm-cta trm-cta-black-out trm-rev&quot;]</value>
   </webElementProperties>
</WebElementEntity>
