<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rebate center</name>
   <tag></tag>
   <elementGuidId>68507d49-f1d1-4479-847c-edbbed8a900b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Rebate center
  </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky-header&quot;)/div[@class=&quot;search-results&quot;]/div[@class=&quot;title-bar&quot;]/div[@class=&quot;search-results-details&quot;]/h1[1]/cvs-record-count[1]/div[@class=&quot;cvs-record-count&quot;]/span[@class=&quot;search-label&quot;]</value>
   </webElementProperties>
</WebElementEntity>
