<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_shop__nav-active</name>
   <tag></tag>
   <elementGuidId>ba079b25-bb08-4b60-a50e-9f9603ed0a56</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop__nav-active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Media/images/shop/buttons/ShopDog-selected.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shop&quot;)/div[@class=&quot;shop__nav&quot;]/div[@class=&quot;shop__nav-inner&quot;]/ul[1]/li[1]/a[@class=&quot;shop__nav-button&quot;]/img[@class=&quot;shop__nav-active&quot;]</value>
   </webElementProperties>
</WebElementEntity>
