<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_2</name>
   <tag></tag>
   <elementGuidId>619e87aa-2eb2-4b75-87a5-31b4a76ad202</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Media/images/shop/buttons/ShopCat.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shop&quot;)/div[@class=&quot;shop__nav&quot;]/div[@class=&quot;shop__nav-inner&quot;]/ul[1]/li[2]/a[@class=&quot;shop__nav-button&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
