<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_trm-image</name>
   <tag></tag>
   <elementGuidId>b2a7ccc2-65bf-4e08-974d-a1c8a2689c22</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static-walmart.secure.footprint.net/PageBuilds/TRF/01_TRF_C7840_ST/2018/img/lifestyle.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trm-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js main-html-body&quot;]/body[@class=&quot;align-center tempo-module&quot;]/div[@class=&quot;trm-trf&quot;]/div[@class=&quot;trm-brandpage&quot;]/div[@class=&quot;trm-col-wrap&quot;]/div[@class=&quot;trm-col-right&quot;]/a[@class=&quot;trm-modsec trm-video-trigger&quot;]/span[@class=&quot;trm-image-wrap&quot;]/img[@class=&quot;trm-image&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Straight Talk Phones Shop all/iframe_iframe-contentZone6</value>
   </webElementProperties>
</WebElementEntity>
