<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ol_Cell PhonesStraight Talk Wi</name>
   <tag></tag>
   <elementGuidId>39ac45cd-9eb9-4b53-83ae-914a7a293548</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ol</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>breadcrumb-list</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemtype</name>
      <type>Main</type>
      <value>//schema.org/BreadcrumbList</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cell Phones/Straight Talk Wireless</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoryContainer&quot;)/div[@class=&quot;CategoryApp&quot;]/div[@class=&quot;CategoryApp-topModules&quot;]/div[@class=&quot;CategoryBreadCrumbs&quot;]/nav[1]/ol[@class=&quot;breadcrumb-list&quot;]</value>
   </webElementProperties>
</WebElementEntity>
