<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Watchvideo</name>
   <tag></tag>
   <elementGuidId>ad69668b-672b-4d08-a49c-927ce0a5119c</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Watchvideo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;router-content&quot;)/cvs-shop[1]/gb-container[@class=&quot;gb-ui&quot;]/gb-cvs[1]/main[@class=&quot;brandshop brandshop-l gb-ui&quot;]/gb-template[@class=&quot;gbcvs-c-zone gbcvs-c-zone--main gb-ui&quot;]/div[1]/gbcvs-zone-wrapper[@class=&quot;gb-ui&quot;]/section[@class=&quot;gbcvs-c-sectionBlock gbcvs-c-sectionBlock--rcz&quot;]/div[@class=&quot;gbcvs-c-sectionBlock__inner&quot;]/div[@class=&quot;gb-ui&quot;]/gb-raw[@class=&quot;gb-ui&quot;]/section[@class=&quot;trm-sections trm-tag-parent&quot;]/div[@class=&quot;trm-grid trm-body-wrap&quot;]/div[@class=&quot;trm-stacked-hero trm-stacked-hero-expand trm-row&quot;]/div[@class=&quot;trm-stack-expand&quot;]/a[@class=&quot;trm-see-more trm-tr yt-init&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='router-content']/cvs-shop/gb-container/gb-cvs/main/gb-template[10]/div/gbcvs-zone-wrapper/section/div/div/gb-raw/section/div/div/div[2]/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registered Dietitian, Mia Syn, explains why you should take a probiotic daily!'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Probiotics 101: Learn more about gut health'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/a/span</value>
   </webElementXpaths>
</WebElementEntity>
