<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Husky Straight</name>
   <tag></tag>
   <elementGuidId>938d973c-93ea-4512-8352-1cc8299d1247</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.walmart.com/ip/Signature-by-Levi-Strauss-Co.-Boys-Husky-Straight-Jeans/16423424</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trackMe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>omnitag</name>
      <type>Main</type>
      <value>boys-husky-straight</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>omniint</name>
      <type>Main</type>
      <value>link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>s_objectID=&quot;http://www.walmart.com/ip/Signature-by-Levi-Strauss-Co.-Boys-Husky-Straight-Jeans/16423424_2&quot;;return this.s_oc?this.s_oc(e):true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Husky Straight</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trmWrap&quot;)/div[@class=&quot;trm-main&quot;]/div[@class=&quot;Grid trm-top&quot;]/div[@class=&quot;Grid-col u-size-7-10 trm-right trm-top-right&quot;]/nav[@class=&quot;nav desk&quot;]/div[@class=&quot;trm-menu Grid text-left&quot;]/div[@class=&quot;Grid-col u-size-1-5 menu&quot;]/div[@class=&quot;navdropdown&quot;]/ul[1]/li[6]/a[@class=&quot;trackMe&quot;]</value>
   </webElementProperties>
</WebElementEntity>
