<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Low-Rise Jogger Jeans</name>
   <tag></tag>
   <elementGuidId>52abfcb8-8469-4432-bc16-cecbd1afbd56</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.walmart.com/ip/Signature-by-Levi-Strauss-Co-Juniors-Low-Rise-Boyfriend-Jeans/55779399?variantFieldId=actual_color</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trackMe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>omnitag</name>
      <type>Main</type>
      <value>juniors-Jogger_Jeans</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>omniint</name>
      <type>Main</type>
      <value>link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>s_objectID=&quot;https://www.walmart.com/ip/Signature-by-Levi-Strauss-Co-Juniors-Low-Rise-Boyfriend-Jeans/55779399_2&quot;;return this.s_oc?this.s_oc(e):true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Low-Rise Jogger Jeans</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trmWrap&quot;)/div[@class=&quot;trm-main&quot;]/div[@class=&quot;Grid trm-top&quot;]/div[@class=&quot;Grid-col u-size-7-10 trm-right trm-top-right&quot;]/nav[@class=&quot;nav desk&quot;]/div[@class=&quot;trm-menu Grid text-left&quot;]/div[@class=&quot;Grid-col u-size-1-5 menu&quot;]/div[@class=&quot;navdropdown&quot;]/ul[1]/li[3]/a[@class=&quot;trackMe&quot;]</value>
   </webElementProperties>
</WebElementEntity>
