<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shorts  Capris</name>
   <tag></tag>
   <elementGuidId>49775459-ecab-409f-a009-86ce49981519</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trackMe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>omniint</name>
      <type>Main</type>
      <value>Link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>omnitag</name>
      <type>Main</type>
      <value>Link_ShortsCapris</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.walmart.com/browse/clothing/womens-shorts/riders-by-lee/5438_133162_8865361/YnJhbmQ6UmlkZXJzIGJ5IExlZQieie?cat_id=5438_133162_8865361&amp;facet=brand%3ARiders+by+Lee&amp;sort=new#searchProductResult</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>s_objectID=&quot;https://www.walmart.com/browse/clothing/womens-shorts/riders-by-lee/5438_133162_8865361/YnJhbmQ6U_1&quot;;return this.s_oc?this.s_oc(e):true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shorts &amp; Capris</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_C001_divContent&quot;)/div[@class=&quot;trmBodyContent&quot;]/main[@class=&quot;trm-main&quot;]/header[1]/nav[@class=&quot;trm-nav-wrap Grid&quot;]/div[@class=&quot;trm-nav Grid-col u-size-1-2 vb&quot;]/ul[1]/li[1]/ul[@class=&quot;submenu&quot;]/li[3]/a[@class=&quot;trackMe&quot;]</value>
   </webElementProperties>
</WebElementEntity>
