<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>582b7f04-8a2b-4c8f-a8ee-10094e630416</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MediaOMP/2018/BIC/01_BIC_Q9308_BICBTS2018/img/pov-arrow-right.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_C001_divContent&quot;)/div[@class=&quot;trmBodyContent&quot;]/div[@class=&quot;trm-pagewrap&quot;]/div[@class=&quot;trm-container&quot;]/div[@class=&quot;trm-pov-slider&quot;]/div[@class=&quot;trm-pov-mod&quot;]/a[@class=&quot;trackMe&quot;]/div[@class=&quot;trm-pov-card&quot;]/div[@class=&quot;trm-pov-card-footer&quot;]/i[@class=&quot;trm-desk&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
