<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>5987806c-e352-4941-a3d9-9a8f7a2a9311</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginator-hairline-btn js-paginator-btn js-paginator-btn-next paginator-hairline-btn-next paginator-hairline-btn-positioned paginator-hairline-btn-voffset paginator-hairline-btn-full-height trackMe slick-arrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>omnitag</name>
      <type>Main</type>
      <value>Products Next Slide</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>omniint</name>
      <type>Main</type>
      <value>interaction</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_C001_divContent&quot;)/div[@class=&quot;trmBodyContent&quot;]/div[@class=&quot;trm-page-wrap&quot;]/div[@class=&quot;trm-product-wrap&quot;]/div[@class=&quot;trm-product-row&quot;]/div[@class=&quot;trm-pro-right&quot;]/div[@id=&quot;dynpricing-scroller&quot;]/button[@class=&quot;paginator-hairline-btn js-paginator-btn js-paginator-btn-next paginator-hairline-btn-next paginator-hairline-btn-positioned paginator-hairline-btn-voffset paginator-hairline-btn-full-height trackMe slick-arrow&quot;]</value>
   </webElementProperties>
</WebElementEntity>
