<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ef453d1f-6d68-4632-be88-6ef4aa70bfa6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MediaOMP/2018/SCJ/01_SCJ_S0516_ZiplocNutcrackerHol2018/img/prev.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>previous</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_C001_divContent&quot;)/div[@class=&quot;trmBodyContent&quot;]/div[@class=&quot;trm-page-wrap&quot;]/div[@class=&quot;trm-mod-slider&quot;]/div[@class=&quot;trm-slide-right&quot;]/div[@class=&quot;trm-mod-slide slick-initialized slick-slider&quot;]/button[@class=&quot;trm-lrg-prev paginator-hairline-btn js-paginator-btn js-paginator-btn-prev paginator-hairline-btn-prev paginator-hairline-btn-positioned paginator-hairline-btn-voffset paginator-hairline-btn-full-height trackMe slick-arrow&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
