<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_pov-dsk</name>
   <tag></tag>
   <elementGuidId>60a9e3e1-e21a-4885-8950-afc6f1af2442</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MediaOMP/2018/GYR/01_GYR_P7114_NewOutlast18/img/pov0.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pov-dsk</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_wrap&quot;)/div[@class=&quot;fullwidth_wrap clear&quot;]/div[@class=&quot;inner_wrap clear&quot;]/div[@class=&quot;trm-pov-slide one-time slick-initialized slick-slider slick-dotted&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;trm-pov pov-first slick-slide slick-current slick-active&quot;]/img[@class=&quot;pov-dsk&quot;]</value>
   </webElementProperties>
</WebElementEntity>
