<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_trm-povimage</name>
   <tag></tag>
   <elementGuidId>e7ad607e-7f3c-443c-9d04-b679b70021af</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MediaOMP/2018/SKW/01_SKW_Q3813_Skyworth/img/skyworth-tv.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trm-povimage</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_C001_divContent&quot;)/div[@class=&quot;trmBodyContent&quot;]/main[@class=&quot;trm-skw&quot;]/section[@class=&quot;trm-design&quot;]/div[@class=&quot;trm-pov-mod&quot;]/a[@class=&quot;trm-pov-slide trackMe&quot;]/div[@class=&quot;trm-povimagwrap&quot;]/img[@class=&quot;trm-povimage&quot;]</value>
   </webElementProperties>
</WebElementEntity>
