<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Centrum</name>
   <tag></tag>
   <elementGuidId>dc0158fe-c2d3-4914-9d9a-d530db90c896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='router-content']/cvs-shop/gb-container/gb-cvs/main/gb-template[3]/div/div/gbcvs-page-hd/section/div/div/h1/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Centrum</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;router-content&quot;)/cvs-shop[1]/gb-container[@class=&quot;gb-ui&quot;]/gb-cvs[1]/main[@class=&quot;brandshop brandshop-l gb-ui&quot;]/gb-template[@class=&quot;gbcvs-c-zone gbcvs-c-zone--pageHd gb-ui&quot;]/div[1]/div[@class=&quot;gbcvs-c-sectionBlock gbcvs-c-sectionBlock--pageHd&quot;]/gbcvs-page-hd[@class=&quot;gb-ui&quot;]/section[@class=&quot;gbcvs-c-pageHd gbcvs-c-pageHd--bottomBorder&quot;]/div[@class=&quot;gbcvs-c-pageHd__inner gbcvs-c-pageHd__inner--gutterSpace&quot;]/div[@class=&quot;gbcvs-c-pageHd__l-left&quot;]/h1[@class=&quot;gbcvs-c-pageHd__heading&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='router-content']/cvs-shop/gb-container/gb-cvs/main/gb-template[3]/div/div/gbcvs-page-hd/section/div/div/h1/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='brand shop'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[2]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feed your cells'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='®'])[4]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//h1/span</value>
   </webElementXpaths>
</WebElementEntity>
