<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Item 277847 (1)</name>
   <tag></tag>
   <elementGuidId>4188bf61-ac51-48b7-bb78-d64b0c353a27</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productView</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>products jqQuickView grid_view</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-truncate-desc</name>
      <type>Main</type>
      <value>{
      &quot;descriptionTruncateLengthChar1&quot; : 80,
      &quot;descriptionTruncateLengthChar2&quot; : 300
    }</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tabpanel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 277847
                            
                        
                    
                    
                        
                            
                                
                                
                                    3 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Guest Chair, Black/Black
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $72.79 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 282468
                            
                        
                    
                    
                        
                            
                                
                                
                                    0 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Heavy-Duty Leather High-Back Chair, Black
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $252.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 346548
                            
                        
                    
                    
                        
                            
                                
                                
                                    0 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Diamond Stacking Chair, Black
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $44.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 359290
                            
                        
                    
                    
                        
                            
                                
                                
                                    2 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Office Products Traditional Tufted Conference Chair With Casters, 31&quot;H x 24&quot;W x 26&quot;D, Mahogany/Black
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $112.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 359308
                            
                        
                    
                    
                        
                            
                                
                                
                                    2 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Office Products Traditional Tufted Conference Chair With Casters, 31&quot;H x 24&quot;W x 26&quot;D, Mahogany/Oxblood
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $112.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 385629
                            
                        
                    
                    
                        
                            
                                
                                
                                    1 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Office Products Traditional High-Back Executive Chair, 47&quot;H x 27&quot;W x 28&quot;D, Mahogany Frame, Black Vinyl
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $182.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 386502
                            
                        
                    
                    
                        
                            
                                
                                
                                    5 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Medical Stool With Back And Foot Ring And Antimicrobial Vinyl, 47&quot;H x 25&quot;W x 25&quot;D, Black/Chrome
                            
                        
                    
                    
                        
                        
                            
                                    
						                $94.99
						                each (Reg)
                                    
                                    
                                         $75.99 SALE
                                        
                                            
                                                (save $19)
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 607744
                            
                        
                    
                    
                        
                            
                                
                                
                                    11 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Office Products Traditional Tufted Conference Chair, 31&quot;H x 24&quot;W x 26&quot;D, Mahogany Frame, Black Vinyl
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $104.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 607753
                            
                        
                    
                    
                        
                            
                                
                                
                                    2 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Office Products Traditional Tufted Conference Chair, 31&quot;H x 24&quot;W x 26&quot;D, Mahogany Frame, Oxblood Vinyl
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $104.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 679603
                            
                        
                    
                    
                        
                            
                                
                                
                                    9 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Heavy-Duty Big &amp; Tall Executive Chair, 45 1/2&quot;H x 30 1/2&quot;W x 27&quot;D, Black CaressoftPlus™ Vinyl
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $239.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 679666
                            
                        
                    
                    
                        
                            
                                
                                
                                    1 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Heavy-Duty Big &amp; Tall Executive High-Back Chair, Black
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $244.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 738152
                            
                        
                    
                    
                        
                            
                                
                                
                                    0 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Modern Executive Vinyl Conference Chair, High Back, Black/Black
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $260.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 831231
                            
                        
                    
                    
                        
                            
                                
                                
                                    13 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Office Products Leather Contoured Guest Chair, 34 1/2&quot;H x 23&quot;W x 24 1/2&quot;D, Black Frame, Black Leather
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $79.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 834571
                            
                        
                    
                    
                        
                            
                                
                                
                                    6 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss® Wide Seat Fabric Task Chair, 35&quot;H x 19&quot;W x 21&quot;D, Black Frame, Black Fabric
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $69.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 1759195
                            
                        
                    
                    
                        
                            
                                
                                
                                    2 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Drafting Stool, Black/Chrome
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $92.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 1825273
                            
                        
                    
                    
                        
                            
                                
                                
                                    2 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Fabric Drafting Stool, Black/Chrome
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $129.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 1825282
                            
                        
                    
                    
                        
                            
                                
                                
                                    8 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Multi-Function Budget Drafting Stool, Black/Chrome
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $134.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 1825309
                            
                        
                    
                    
                        
                            
                                
                                
                                    2 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Heavy-Duty Mid-Back Task Chair, Black
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $142.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 1826101
                            
                        
                    
                    
                        
                            
                                
                                
                                    3 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Drafting Stool, Blue/Chrome
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $84.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 1826182
                            
                        
                    
                    
                        
                            
                                
                                
                                    1 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Drafting Stool, Black
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $104.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        
        
            
            
            
            
            
            
            
            
            
                
                    
                        
                            
                        
                        
                    
                    

                    
                
                
                    
                    
                        
                            Item 1826290
                            
                        
                    
                    
                        
                            
                                
                                
                                    0 Reviews 
                                
                            
                        
                    

                    
                        
                            
                                Boss Drafting Stool, Black/Chrome
                            
                        
                    
                    
                        
                        
                            
                                    
                                         $119.99 
                                        
                                            
                                                each
                                            
                                        
                                    
                                
                            
                        
                        
                        
                            
                               
                                
                                   
                                    Shop Now
                                
                            
                            
                        
                    
                    
                        
                    
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                    
                                
                            
                        
                        
                            
                        
                    
                
            
        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productView&quot;)</value>
   </webElementProperties>
</WebElementEntity>
