<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-rw (5)</name>
   <tag></tag>
   <elementGuidId>7eaaa7ad-c857-43d9-85b6-bb9cfde9010b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-rw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-img</name>
      <type>Main</type>
      <value>feat-prod03.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ADA approved children’s dental products</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//staging.cvs.triadretail.net/shop-assets/04_CVS_P3111_CVSADA18/img/feat-prod03.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;trm-page-wrap&quot;]/div[@class=&quot;trm-width-lock trm-grid&quot;]/div[@class=&quot;trm-body-load&quot;]/div[@class=&quot;trm-bs trm-grid&quot;]/div[@class=&quot;trm-body-wrap&quot;]/div[@class=&quot;trm-grid&quot;]/div[@class=&quot;trm-row trm-stroke trm-feat-cats trm-tag-parent&quot;]/div[@class=&quot;trm-row trm-fc-row&quot;]/div[@class=&quot;col-1-4&quot;]/img[@class=&quot;img-rw&quot;]</value>
   </webElementProperties>
</WebElementEntity>
