<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-rw (2)</name>
   <tag></tag>
   <elementGuidId>2400a881-e2a7-454e-ab74-8b52d01d75b3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-rw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-img</name>
      <type>Main</type>
      <value>grid01-prod03.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//staging.cvs.triadretail.net/shop-assets/04_PFZ_T3341_PFZCCFSpon18/img/grid01-prod03.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;trm-page-wrap&quot;]/div[@class=&quot;trm-width-lock trm-grid&quot;]/div[@class=&quot;trm-body-load&quot;]/div[@class=&quot;trm-body-wrap&quot;]/div[@class=&quot;trm-module-2&quot;]/section[@class=&quot;trm-gb-grid trm-tag-parent&quot;]/div[@id=&quot;promo-category-grid&quot;]/nav[1]/div[@class=&quot;category-sect col-xxs-8 col-xs-8 col-sm-4 col-md-3&quot;]/a[@class=&quot;trm-tr&quot;]/div[@class=&quot;category-box&quot;]/div[@class=&quot;category-box-image&quot;]/img[@class=&quot;img-rw&quot;]</value>
   </webElementProperties>
</WebElementEntity>
