<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-responsive</name>
   <tag></tag>
   <elementGuidId>560339cf-927a-4590-a3c4-e0551ab728d6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/mediaSF/img/thumb-wellness-zone.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Health Checklist</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;center-links&quot;)/div[@class=&quot;col-sm-12 col-md-12 col-lg-12&quot;]/div[@class=&quot;row safe-area center-block&quot;]/div[@class=&quot;col-xs-6 col-ts-3 col-sm-5ths col-md-5ths col-lg-5ths hidden-xs&quot;]/div[@class=&quot;center-teaser&quot;]/a[1]/img[@class=&quot;img-responsive&quot;]</value>
   </webElementProperties>
</WebElementEntity>
