<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>aeb19ddc-1f15-4469-b80b-16970ed745dd</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MediaOMP/2018/MAR/01_MAR_M7759_NutroPetFood/img/d1a.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trm-wrap&quot;)/div[@class=&quot;trm-container&quot;]/div[@class=&quot;trm-tool-section&quot;]/div[@class=&quot;trm-tool-container&quot;]/a[@class=&quot;active trackMe&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
