<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>5252def2-3959-4ec7-987f-7e7c515ee70f</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//ad.doubleclick.net/ddm/adi/N5767.3145464TRIADRETAILMEDIA-SA/B21733799.229754029;dc_ver=45.119;dc_eid=40004000;sz=300x250;u_sd=1;u=__AP1_np_mo_%5BInsertCachebusterHere%5DPA__;dc_adk=1066843466;ord=sgdyrz;click=https%3A%2F%2Fadclick.g.doubleclick.net%2Fpcs%2Fclick%3Fxai%3DAKAOjssm9ajNS611V-rELGQPqc5nANWlCW605z_oA2jAKz5WUkXaYW_30ZjyItbfrsfh7Lx3VNvfp1c9bcTHYUHk_a_Z4heQXWTb9ZnVKULGYvNhMgLcEez0wlCpRrTT7PMMYuK6UMhlZ11vZwvd4GkJSe3i0E-HkHFws6OAv6G8frdHlcADmD7LKbowJPs1GQAUG5ZfbJ_Q05MIHAg_E0WQZnoX_JFvMqlvpae8pUOlgDTIvJyQ%26sai%3DAMfl-YTg2iA_gQao3ew4m2wZb7F9Rt6-WT3PSfq7Y3UZc4oOHUycOsnFpEioZqQuGTwXjxkPerfec9wN3rY9qvqd_1ONLcA3ge69YNx8iDQUH5ZckDw0FgW9Zhs1q9UY%26sig%3DCg0ArKJSzAa0bAGsYzL6EAE%26urlfix%3D1%26adurl%3D;dc_rfl=2,https%3A%2F%2Fwww.cvs.com%2Fshop%2Fbrand-shop%2Fv%2Fvitafusion$0;xdt=1;crlt=)h5kjBqMY5;osda=2;sttr=63;prcl=n?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ins[@class=&quot;dcmads&quot;]/iframe[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Vitafusion  CVS.com/iframe_concat(html1body1iframe</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/html[1]/body[1]/ins[@class=', '&quot;', 'dcmads', '&quot;', ']/iframe[1]')])[1]/preceding::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
