<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Multi-cat</name>
   <tag></tag>
   <elementGuidId>96f866ce-421b-461e-bb7a-6545fde03987</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clean-paws</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Multi-cat</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trmWrap&quot;)/div[@class=&quot;trm-row trm-meet-family&quot;]/div[@class=&quot;trm-family-content&quot;]/div[@class=&quot;trm-content&quot;]/div[@class=&quot;trm-family-cont-sec trm-desktop&quot;]/div[@class=&quot;trm-family-cont active&quot;]/div[@class=&quot;trm-pink-tab trm-pink-first&quot;]/ul[1]/li[@class=&quot;clean-paws&quot;]</value>
   </webElementProperties>
</WebElementEntity>
