<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-rw (1)</name>
   <tag></tag>
   <elementGuidId>8da5a571-0b06-400c-9176-58dcb069954f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-rw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-img</name>
      <type>Main</type>
      <value>feat-prod02.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Rhinocort 120ct and Rhinocort 60ct</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//staging.cvs.triadretail.net/shop-assets/04_JNJ_N1073_Allergy2018/img/feat-prod02.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;trm-page-wrap&quot;]/div[@class=&quot;trm-width-lock trm-grid&quot;]/div[@class=&quot;trm-body-load&quot;]/div[@class=&quot;trm-bs trm-grid&quot;]/div[@class=&quot;trm-body-wrap&quot;]/div[@class=&quot;trm-grid&quot;]/div[@class=&quot;trm-row trm-stroke trm-feat-cats trm-tag-parent&quot;]/div[@class=&quot;trm-row&quot;]/div[@class=&quot;col-1-3&quot;]/img[@class=&quot;img-rw&quot;]</value>
   </webElementProperties>
</WebElementEntity>
