<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_FriXion erasable pens write</name>
   <tag></tag>
   <elementGuidId>c3784bf5-7bda-4336-a0e7-61900392e107</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FriXion erasable pens write smoothly &amp; erase cleanly without any wear &amp; tear to the paper or messy eraser crumbs. The perfect alternative to traditional pens &amp; pencils, FriXion offers unlimited do-overs so you can write, erase &amp; re-write until you get it right. The heat generated by erasing FriXion causes our unique thermos-sensitive ink to become clear &amp; the writing to disappear from the page. Make written mistakes a thing of the past with FriXion. Write fearlessly!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_C001_divContent&quot;)/div[@class=&quot;trmBodyContent&quot;]/div[@class=&quot;trm-pagewrap&quot;]/div[@class=&quot;trm-container&quot;]/div[@class=&quot;trm-inner-container&quot;]/div[@class=&quot;trm-product-section&quot;]/div[@class=&quot;trm-product-head&quot;]/div[@class=&quot;trm-product-contant&quot;]/p[1]</value>
   </webElementProperties>
</WebElementEntity>
