<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (3)</name>
   <tag></tag>
   <elementGuidId>8db8e1da-adc6-4b49-9141-e989ccfd4c5f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MediaOMP/2017/CLX/01_CLX_J5535_BBBP5Up/img/goodness-glows-liquid.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>goodness-glows-liquid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_wrap&quot;)/div[@class=&quot;fullwidth_wrap&quot;]/div[@class=&quot;inner_wrap&quot;]/div[@class=&quot;trm-products-detail&quot;]/div[@class=&quot;trm-product-cont&quot;]/div[@class=&quot;trm-products-slide&quot;]/div[@class=&quot;prod-graphic&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
