<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_d__products_all</name>
   <tag></tag>
   <elementGuidId>1d5f08f4-c61d-442d-b8f2-b420d5cc7ff3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Media/images/desktop/last_mod_all_products.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d__products_all</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MasterForm&quot;)/div[@class=&quot;positionRelative&quot;]/section[@class=&quot;main_content_full_C&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;col-lg-7 col-md-7 col-sm-12 col-xs-12 m__last_mod_bg&quot;]/img[@class=&quot;d__products_all&quot;]</value>
   </webElementProperties>
</WebElementEntity>
