<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_H2s</name>
   <tag></tag>
   <elementGuidId>de9604f0-f5e3-4e1d-9132-5df99d095b90</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trm-artlce-title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            H2s
                            Histamine blockers block a signal that tells your body to make acid. H2s start working within 30 minutes and can last up to 12 hours, but may become less effective after a few days.
                        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;router-content&quot;)/cvs-shop[1]/gb-container[@class=&quot;gb-ui&quot;]/gb-cvs[1]/main[@class=&quot;brandshop brandshop-l gb-ui&quot;]/gb-template[@class=&quot;gbcvs-c-zone gbcvs-c-zone--main gb-ui&quot;]/div[1]/gbcvs-zone-wrapper[@class=&quot;gb-ui&quot;]/section[@class=&quot;gbcvs-c-sectionBlock gbcvs-c-sectionBlock--rcz&quot;]/div[@class=&quot;gbcvs-c-sectionBlock__inner&quot;]/div[@class=&quot;gb-ui&quot;]/gb-raw[@class=&quot;gb-ui&quot;]/section[@class=&quot;trm-sections trm-full-width trm-custom-bg trm-tag-parent&quot;]/div[@class=&quot;trm-grid trm-body-wrap&quot;]/div[@class=&quot;trm-article-section&quot;]/div[@class=&quot;trm-row&quot;]/div[@class=&quot;trm-col-xs-12 trm-col-sm-4&quot;]/div[@class=&quot;trm-artlce-title&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='router-content']/cvs-shop/gb-container/gb-cvs/main/gb-template[6]/div/gbcvs-zone-wrapper/section/div/div/gb-raw/section/div/div/div/div[3]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Antacids'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='®'])[9]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Can you imagine chocolate without heartburn?'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//gb-template[6]/div/gbcvs-zone-wrapper/section/div/div/gb-raw/section/div/div/div/div[3]/div</value>
   </webElementXpaths>
</WebElementEntity>
